### ISSUE TITLE
Suggestion for improvements

### ISSUE THREAD

**Issue by andredias** [sglibova/perfect_python_project#1]
The project is very good! There are only some little :

1. the task `test_only` in `Makeflie` calls `pytest` three times. I suggest that you use the second call but add the parameters of the third.
2. I miss some additional configuration for tools such as `isort`, `flake8` and `mypy`. Except for `flake8` you can keep other configurations inside `pyproject.toml`. For, `isort` for example, a good option is to configure `profile` and `line_length`. `mypy` has a few interesting options too.
3. `poetry.lock` shouldn't be in `.gitignore`. It is important to share it among developers so everyone use the same versions.

**Comment by sglibova** [comment]
Done! Thank you!
